# Site settings
version: 0.5

title: Breakfast with a Geek
email: geekbreakfast@gmail.com
description: Two geeks meeting almost every morning to have a conversation about everything and anything
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: none
url: "http://geekbreakfast.it" # the base hostname & protocol for your site
twitter_username: _geekbreakfast
github_username:  geekbreakfast
twitter_alessandro: lord2y
twitter_joern: joernba

# Build settings
markdown: kramdown
sass:
    style: compressed
